# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=155, unique=True)),
                ('your_suggestion', models.TextField(help_text='brief informartion that you think we should include when developing the web application.')),
            ],
        ),
    ]
