# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_suggestion_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ('-id',)},
        ),
    ]
