# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_auto_20170810_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='your_suggestion',
            field=models.TextField(help_text='brief info.'),
        ),
    ]
