# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0006_auto_20170810_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Image'),
        ),
    ]
