# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0007_auto_20170810_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default='caption', max_length=155),
            preserve_default=False,
        ),
    ]
